// Mock data for fallback (snake_case to match DB columns)
const mockProducts = [
    {
        id: 1,
        name: "Wireless Noise-Cancelling Headphones",
        slug: "wireless-noise-cancelling-headphones",
        description: "Experience premium sound quality with our latest noise-cancelling technology.",
        short_description: "Premium wireless headphones with ANC",
        sku: "HEAD-001",
        price: 299.99,
        compare_price: 349.99,
        cost_price: 150.00,
        stock_quantity: 50,
        low_stock_threshold: 5,
        weight: 0.5,
        dimensions: { length: 20, width: 18, height: 8 },
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80"],
        is_active: true,
        is_featured: true,
        meta_title: "Wireless Headphones - Premium Sound",
        meta_description: "Best wireless headphones with noise cancellation",
        tags: ["electronics", "audio", "wireless"],
        category_name: "Audio",
        category_slug: "audio",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        total_count: 4
    },
    {
        id: 2,
        name: "Smart Fitness Watch",
        slug: "smart-fitness-watch",
        description: "Track your health and fitness goals with this advanced smartwatch.",
        short_description: "Water-resistant fitness tracker",
        sku: "WATCH-002",
        price: 199.99,
        compare_price: null,
        cost_price: 90.00,
        stock_quantity: 100,
        low_stock_threshold: 10,
        weight: 0.1,
        dimensions: { length: 4, width: 4, height: 1 },
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80"],
        is_active: true,
        is_featured: true,
        meta_title: "Smart Fitness Watch",
        meta_description: "Track your fitness",
        tags: ["electronics", "wearable", "fitness"],
        category_name: "Wearables",
        category_slug: "wearables",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        total_count: 4
    },
    {
        id: 3,
        name: "Professional Camera Lens",
        slug: "professional-camera-lens",
        description: "Capture stunning photos with this high-aperture lens.",
        short_description: "50mm f/1.8 Prime Lens",
        sku: "LENS-003",
        price: 499.99,
        compare_price: 599.99,
        cost_price: 300.00,
        stock_quantity: 15,
        low_stock_threshold: 2,
        weight: 0.4,
        dimensions: { length: 7, width: 7, height: 6 },
        images: ["https://images.unsplash.com/photo-1617005082133-548c4dd27f35?w=800&q=80"],
        is_active: true,
        is_featured: false,
        meta_title: "Pro Camera Lens",
        meta_description: "Upgrade your photography",
        tags: ["electronics", "photography", "camera"],
        category_name: "Photography",
        category_slug: "photography",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        total_count: 4
    },
    {
        id: 4,
        name: "Mechanical Gaming Keyboard",
        slug: "mechanical-gaming-keyboard",
        description: "RGB mechanical keyboard with cherry mx switches.",
        short_description: "RGB Mechanical Keyboard",
        sku: "KEY-004",
        price: 129.99,
        compare_price: 159.99,
        cost_price: 60.00,
        stock_quantity: 200,
        low_stock_threshold: 20,
        weight: 1.2,
        dimensions: { length: 45, width: 15, height: 4 },
        images: ["https://images.unsplash.com/photo-1587829741301-3e4b78917eaf?w=800&q=80"],
        is_active: true,
        is_featured: true,
        meta_title: "Gaming Keyboard",
        meta_description: "Best mechanical keyboard for gaming",
        tags: ["electronics", "computer", "gaming"],
        category_name: "Computer Accessories",
        category_slug: "computer-accessories",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        total_count: 4
    },
    {
        id: 5,
        name: "Ultra-Slim Laptop Pro",
        slug: "ultra-slim-laptop-pro",
        short_description: "14-inch retina display, M2 Chip",
        price: 12999,
        compare_price: 14999,
        stock_quantity: 45,
        images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80"],
        is_active: true,
        is_featured: true,
        category_name: "Computers",
        category_slug: "computers",
        total_count: 10
    },
    {
        id: 6,
        name: "Wireless Charging Pad",
        slug: "wireless-charging-pad",
        short_description: "Fast charging for all Qi devices",
        price: 349,
        compare_price: 499,
        stock_quantity: 200,
        images: ["https://images.unsplash.com/photo-1615526775267-897db465243e?w=800&q=80"],
        is_active: true,
        is_featured: false,
        category_name: "Accessories",
        category_slug: "accessories",
        total_count: 10
    },
    {
        id: 7,
        name: "4K Action Camera",
        slug: "4k-action-camera",
        short_description: "Waterproof up to 40m",
        price: 2499,
        compare_price: null,
        stock_quantity: 0,
        images: ["https://images.unsplash.com/photo-1564466964528-21c2d3104e0d?w=800&q=80"],
        is_active: true,
        is_featured: false,
        category_name: "Cameras",
        category_slug: "cameras",
        total_count: 10
    },
    {
        id: 8,
        name: "Bluetooth Portable Speaker",
        slug: "bluetooth-portable-speaker",
        short_description: "20h battery life, deep bass",
        price: 799,
        compare_price: 999,
        stock_quantity: 120,
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80"],
        is_active: true,
        is_featured: true,
        category_name: "Audio",
        category_slug: "audio",
        total_count: 10
    },
    {
        id: 9,
        name: "Smart Home Hub",
        slug: "smart-home-hub",
        short_description: "Control all your devices in one place",
        price: 1499,
        compare_price: 1899,
        stock_quantity: 30,
        images: ["https://images.unsplash.com/photo-1558389659-4ac97594dbf0?w=800&q=80"],
        is_active: true,
        is_featured: true,
        category_name: "Smart Home",
        category_slug: "smart-home",
        total_count: 10
    },
    {
        id: 10,
        name: "Gaming Mouse RGB",
        slug: "gaming-mouse-rgb",
        short_description: "25000 DPI sensor",
        price: 599,
        compare_price: 799,
        stock_quantity: 80,
        images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80"],
        is_active: true,
        is_featured: false,
        category_name: "Gaming",
        category_slug: "gaming",
        total_count: 10
    }
];

module.exports = { mockProducts };
